ZEDCameraSettings Class Reference | API Reference | Stereolabs
ZEDCameraSettings Class Reference
Video Module
Stores the camera settings (brightness/contrast, gain/exposure, etc.) and interfaces with the ZED when they need to be loaded or changed. Created by ZEDCamera and referenced by ZEDCameraSettingsEditor.
Classes
class CameraSettings
Container for ZED camera settings, with constructors for easily creating default or specific values or making duplicate instances.
Functions
ZEDCameraSettings ()
Constructor. Creates a new instance of CameraSettings to contain all settings values.
void SetSettings (sl.ZEDCamera zedCamera)
Applies all settings from the container to the actual ZED camera.
void ResetCameraSettings (sl.ZEDCamera zedCamera)
Applies all settings from the container to the actual ZED camera.
void LoadCameraSettings (sl.ZEDCamera zedCamera, string path="ZED_Settings.conf")
Loads camera settings from a file, and sets them to the container and camera. File is loaded from the root project folder (one above Assets).
void RetrieveSettingsCamera (sl.ZEDCamera zedCamera)
Retrieves current settings from the ZED camera.
void SetCameraSettings (int cid, sl.CAMERA_SETTINGS settings, int value, bool usedefault=false)
Applies an individual setting to the ZED camera.
int GetCameraSettings (int cid, sl.CAMERA_SETTINGS settings)
Gets the value from an individual ZED camera setting (brightness, contrast, gain, exposure, etc.)
void SaveCameraSettings (string path)
Saves all camera settings into a file into the specified path/name.
Attributes
bool auto = true
Whether exposure is set to automatic.
bool whiteBalanceAuto = true
Whether white balance is set to automatic.
Properties
CameraSettings Settings [get]
Reference to the settings container object.
Detailed Description
Stores the camera settings (brightness/contrast, gain/exposure, etc.) and interfaces with the ZED when they need to be loaded or changed. Created by ZEDCamera and referenced by ZEDCameraSettingsEditor.
The actual settings themselves are stored in an instance of CameraSettings, for easier manipulation. But this class provides accessors for each value within it.
Constructor and Destructor
ZEDCameraSettings()
ZEDCameraSettings () inline
Constructor. Creates a new instance of CameraSettings to contain all settings values.
Functions
SetSettings()
void SetSettings (sl.ZEDCamera zedCamera) inline
Applies all settings from the container to the actual ZED camera.
Parameters
zedCamera Current instance of the ZEDCamera wrapper.
Referenced by ZEDCameraSettings.LoadCameraSettings(), and ZEDCamera.SetCameraSettings().
ResetCameraSettings()
void ResetCameraSettings (sl.ZEDCamera zedCamera) inline
Applies all settings from the container to the actual ZED camera.
Parameters
zedCamera Current instance of the ZEDCamera wrapper.
LoadCameraSettings()
void LoadCameraSettings (sl.ZEDCamera zedCamera, string path = "ZED_Settings.conf") inline
Loads camera settings from a file, and sets them to the container and camera. File is loaded from the root project folder (one above Assets).
Parameters
zedCamera
path
Referenced by ZEDCamera.LoadCameraSettings().
RetrieveSettingsCamera()
void RetrieveSettingsCamera (sl.ZEDCamera zedCamera) inline
Retrieves current settings from the ZED camera.
Parameters
zedCamera
Referenced by ZEDCamera.RetrieveCameraSettings().
SetCameraSettings()
void SetCameraSettings (int cid, sl.CAMERA_SETTINGS settings, int value, bool usedefault = false) inline
Applies an individual setting to the ZED camera.
Parameters
settings Setting to be changed (brightness, contrast, gain, exposure, etc.)
value New value for the setting.
usedefault If true, ignores the value and applies the default setting.
GetCameraSettings()
int GetCameraSettings (int cid, sl.CAMERA_SETTINGS settings) inline
Gets the value from an individual ZED camera setting (brightness, contrast, gain, exposure, etc.)
Parameters
settings Setting to be retrieved.
Returns
Current value.
SaveCameraSettings()
void SaveCameraSettings (string path) inline
Saves all camera settings into a file into the specified path/name.
Parameters
path Path and filename to save the file
Referenced by ZEDCamera.SaveCameraSettings().
Variables
auto
bool auto = true
Whether exposure is set to automatic.
Referenced by ZEDCamera.GetExposureUpdateType().
whiteBalanceAuto
bool whiteBalanceAuto = true
Whether white balance is set to automatic.
Referenced by ZEDCamera.GetWhiteBalanceUpdateType(), and ZEDCameraSettings.LoadCameraSettings().
Property Documentation
Settings
CameraSettings Settings get
Reference to the settings container object.