var hierarchy =
[
    [ "allocator< T >", null, null ],
    [ "array< T >", null, null ],
    [ "atomic< T >", null, null ],
    [ "atomic_ref< T >", null, null ],
    [ "auto_ptr< T >", null, null ],
    [ "BarometerData", "structsl_1_1BarometerData.html", null ],
    [ "basic_string< Char >", null, [
      [ "string", null, null ],
      [ "u16string", null, null ],
      [ "u32string", null, null ],
      [ "u8string", null, null ],
      [ "wstring", null, null ]
    ] ],
    [ "basic_string< char >", null, null ],
    [ "basic_string< char16_t >", null, null ],
    [ "basic_string< char32_t >", null, null ],
    [ "basic_string< char8_t >", null, null ],
    [ "basic_string< wchar_t >", null, null ],
    [ "basic_string_view< Char >", null, [
      [ "string_view", null, null ],
      [ "u16string_view", null, null ],
      [ "u32string_view", null, null ],
      [ "u8string_view", null, null ],
      [ "wstring_view", null, null ]
    ] ],
    [ "basic_string_view< char >", null, null ],
    [ "basic_string_view< char16_t >", null, null ],
    [ "basic_string_view< char32_t >", null, null ],
    [ "basic_string_view< char8_t >", null, null ],
    [ "basic_string_view< wchar_t >", null, null ],
    [ "bitset< Bits >", null, null ],
    [ "CalibrationParameters", "structsl_1_1CalibrationParameters.html", null ],
    [ "Camera", "classsl_1_1Camera.html", null ],
    [ "CameraParameters", "structsl_1_1CameraParameters.html", null ],
    [ "char2", "structsl_1_1char2.html", null ],
    [ "char3", "structsl_1_1char3.html", null ],
    [ "char4", "structsl_1_1char4.html", null ],
    [ "Chunk", "structsl_1_1Chunk.html", null ],
    [ "complex", null, null ],
    [ "wstring::const_iterator", null, null ],
    [ "map< K, T >::const_iterator", null, null ],
    [ "unordered_map< K, T >::const_iterator", null, null ],
    [ "u8string::const_iterator", null, null ],
    [ "multimap< K, T >::const_iterator", null, null ],
    [ "u16string::const_iterator", null, null ],
    [ "unordered_multimap< K, T >::const_iterator", null, null ],
    [ "set< K >::const_iterator", null, null ],
    [ "unordered_set< K >::const_iterator", null, null ],
    [ "multiset< K >::const_iterator", null, null ],
    [ "unordered_multiset< K >::const_iterator", null, null ],
    [ "u32string::const_iterator", null, null ],
    [ "basic_string_view< Char >::const_iterator", null, null ],
    [ "array< T >::const_iterator", null, null ],
    [ "vector< T >::const_iterator", null, null ],
    [ "span< T >::const_iterator", null, null ],
    [ "string_view::const_iterator", null, null ],
    [ "wstring_view::const_iterator", null, null ],
    [ "u8string_view::const_iterator", null, null ],
    [ "u16string_view::const_iterator", null, null ],
    [ "u32string_view::const_iterator", null, null ],
    [ "basic_string< Char >::const_iterator", null, null ],
    [ "deque< T >::const_iterator", null, null ],
    [ "string::const_iterator", null, null ],
    [ "list< T >::const_iterator", null, null ],
    [ "forward_list< T >::const_iterator", null, null ],
    [ "string::const_reverse_iterator", null, null ],
    [ "unordered_map< K, T >::const_reverse_iterator", null, null ],
    [ "u8string::const_reverse_iterator", null, null ],
    [ "multimap< K, T >::const_reverse_iterator", null, null ],
    [ "unordered_multimap< K, T >::const_reverse_iterator", null, null ],
    [ "u16string::const_reverse_iterator", null, null ],
    [ "set< K >::const_reverse_iterator", null, null ],
    [ "unordered_set< K >::const_reverse_iterator", null, null ],
    [ "u32string::const_reverse_iterator", null, null ],
    [ "map< K, T >::const_reverse_iterator", null, null ],
    [ "multiset< K >::const_reverse_iterator", null, null ],
    [ "unordered_multiset< K >::const_reverse_iterator", null, null ],
    [ "basic_string_view< Char >::const_reverse_iterator", null, null ],
    [ "array< T >::const_reverse_iterator", null, null ],
    [ "vector< T >::const_reverse_iterator", null, null ],
    [ "span< T >::const_reverse_iterator", null, null ],
    [ "string_view::const_reverse_iterator", null, null ],
    [ "wstring_view::const_reverse_iterator", null, null ],
    [ "u8string_view::const_reverse_iterator", null, null ],
    [ "u16string_view::const_reverse_iterator", null, null ],
    [ "basic_string< Char >::const_reverse_iterator", null, null ],
    [ "u32string_view::const_reverse_iterator", null, null ],
    [ "forward_list< T >::const_reverse_iterator", null, null ],
    [ "deque< T >::const_reverse_iterator", null, null ],
    [ "list< T >::const_reverse_iterator", null, null ],
    [ "wstring::const_reverse_iterator", null, null ],
    [ "deque< T >", null, null ],
    [ "error_category", null, null ],
    [ "error_code", null, null ],
    [ "error_condition", null, null ],
    [ "exception", null, [
      [ "bad_alloc", null, null ],
      [ "bad_cast", null, null ],
      [ "bad_exception", null, null ],
      [ "bad_typeid", null, null ],
      [ "ios_base::failure", null, null ],
      [ "logic_error", null, [
        [ "domain_error", null, null ],
        [ "invalid_argument", null, null ],
        [ "length_error", null, null ],
        [ "out_of_range", null, null ]
      ] ],
      [ "runtime_error", null, [
        [ "overflow_error", null, null ],
        [ "range_error", null, null ],
        [ "underflow_error", null, null ]
      ] ]
    ] ],
    [ "float2", "structsl_1_1float2.html", null ],
    [ "float3", "structsl_1_1float3.html", null ],
    [ "float4", "structsl_1_1float4.html", null ],
    [ "forward_list< T >", null, null ],
    [ "FusedPointCloud", "classsl_1_1FusedPointCloud.html", null ],
    [ "ImuData", "structsl_1_1ImuData.html", null ],
    [ "InitParameters", "classsl_1_1InitParameters.html", null ],
    [ "ios_base", null, [
      [ "basic_ios< char >", null, null ],
      [ "basic_ios< wchar_t >", null, null ],
      [ "basic_ios< Char >", null, [
        [ "basic_istream< char >", null, null ],
        [ "basic_istream< wchar_t >", null, null ],
        [ "basic_ostream< char >", null, null ],
        [ "basic_ostream< wchar_t >", null, null ],
        [ "basic_istream< Char >", null, [
          [ "basic_ifstream< char >", null, null ],
          [ "basic_ifstream< wchar_t >", null, null ],
          [ "basic_iostream< char >", null, null ],
          [ "basic_iostream< wchar_t >", null, null ],
          [ "basic_istringstream< char >", null, null ],
          [ "basic_istringstream< wchar_t >", null, null ],
          [ "basic_ifstream< Char >", null, [
            [ "ifstream", null, null ],
            [ "wifstream", null, null ]
          ] ],
          [ "basic_iostream< Char >", null, [
            [ "basic_fstream< char >", null, null ],
            [ "basic_fstream< wchar_t >", null, null ],
            [ "basic_stringstream< char >", null, null ],
            [ "basic_stringstream< wchar_t >", null, null ],
            [ "basic_fstream< Char >", null, [
              [ "fstream", null, null ],
              [ "wfstream", null, null ]
            ] ],
            [ "basic_stringstream< Char >", null, [
              [ "stringstream", null, null ],
              [ "wstringstream", null, null ]
            ] ]
          ] ],
          [ "basic_istringstream< Char >", null, [
            [ "istringstream", null, null ],
            [ "wistringstream", null, null ]
          ] ],
          [ "istream", null, null ],
          [ "wistream", null, null ]
        ] ],
        [ "basic_ostream< Char >", null, [
          [ "basic_iostream< char >", null, null ],
          [ "basic_iostream< wchar_t >", null, null ],
          [ "basic_ofstream< char >", null, null ],
          [ "basic_ofstream< wchar_t >", null, null ],
          [ "basic_ostringstream< char >", null, null ],
          [ "basic_ostringstream< wchar_t >", null, null ],
          [ "basic_iostream< Char >", null, null ],
          [ "basic_ofstream< Char >", null, [
            [ "ofstream", null, null ],
            [ "wofstream", null, null ]
          ] ],
          [ "basic_ostringstream< Char >", null, [
            [ "ostringstream", null, null ],
            [ "wostringstream", null, null ]
          ] ],
          [ "ostream", null, null ],
          [ "wostream", null, null ]
        ] ],
        [ "ios", null, null ],
        [ "wios", null, null ]
      ] ]
    ] ],
    [ "forward_list< T >::iterator", null, null ],
    [ "map< K, T >::iterator", null, null ],
    [ "unordered_map< K, T >::iterator", null, null ],
    [ "multimap< K, T >::iterator", null, null ],
    [ "unordered_multimap< K, T >::iterator", null, null ],
    [ "u16string::iterator", null, null ],
    [ "set< K >::iterator", null, null ],
    [ "u32string::iterator", null, null ],
    [ "unordered_set< K >::iterator", null, null ],
    [ "multiset< K >::iterator", null, null ],
    [ "unordered_multiset< K >::iterator", null, null ],
    [ "basic_string_view< Char >::iterator", null, null ],
    [ "array< T >::iterator", null, null ],
    [ "vector< T >::iterator", null, null ],
    [ "span< T >::iterator", null, null ],
    [ "string_view::iterator", null, null ],
    [ "wstring_view::iterator", null, null ],
    [ "u8string_view::iterator", null, null ],
    [ "u16string_view::iterator", null, null ],
    [ "basic_string< Char >::iterator", null, null ],
    [ "u32string_view::iterator", null, null ],
    [ "string::iterator", null, null ],
    [ "deque< T >::iterator", null, null ],
    [ "wstring::iterator", null, null ],
    [ "u8string::iterator", null, null ],
    [ "list< T >::iterator", null, null ],
    [ "jthread", null, null ],
    [ "list< T >", null, null ],
    [ "lock_guard< T >", null, null ],
    [ "MagnetometerData", "structsl_1_1MagnetometerData.html", null ],
    [ "map< K, T >", null, null ],
    [ "Mat", "classsl_1_1Mat.html", null ],
    [ "Matrix3x3", "structsl_1_1Matrix3x3.html", null ],
    [ "Mesh", "classsl_1_1Mesh.html", null ],
    [ "multimap< K, T >", null, null ],
    [ "multiset< K >", null, null ],
    [ "mutex", null, null ],
    [ "ObjectData", "structsl_1_1ObjectData.html", null ],
    [ "ObjectDetectionParameters", "structsl_1_1ObjectDetectionParameters.html", null ],
    [ "ObjectDetectionRuntimeParameters", "structsl_1_1ObjectDetectionRuntimeParameters.html", null ],
    [ "Objects", "structsl_1_1Objects.html", null ],
    [ "PlaneData", "structsl_1_1PlaneData.html", null ],
    [ "Pose", "structsl_1_1Pose.html", null ],
    [ "PositionalTrackingParameters", "classsl_1_1PositionalTrackingParameters.html", null ],
    [ "priority_queue< T >", null, null ],
    [ "queue< T >", null, null ],
    [ "RecordingParameters", "structsl_1_1RecordingParameters.html", null ],
    [ "RecordingStatus", "structsl_1_1RecordingStatus.html", null ],
    [ "Rect", "structsl_1_1Rect.html", null ],
    [ "recursive_mutex", null, null ],
    [ "recursive_timed_mutex", null, null ],
    [ "Resolution", "structsl_1_1Resolution.html", null ],
    [ "list< T >::reverse_iterator", null, null ],
    [ "forward_list< T >::reverse_iterator", null, null ],
    [ "string::reverse_iterator", null, null ],
    [ "unordered_set< K >::reverse_iterator", null, null ],
    [ "basic_string< Char >::reverse_iterator", null, null ],
    [ "u16string_view::reverse_iterator", null, null ],
    [ "u8string::reverse_iterator", null, null ],
    [ "multimap< K, T >::reverse_iterator", null, null ],
    [ "u32string_view::reverse_iterator", null, null ],
    [ "u16string::reverse_iterator", null, null ],
    [ "span< T >::reverse_iterator", null, null ],
    [ "u32string::reverse_iterator", null, null ],
    [ "unordered_map< K, T >::reverse_iterator", null, null ],
    [ "deque< T >::reverse_iterator", null, null ],
    [ "unordered_multiset< K >::reverse_iterator", null, null ],
    [ "array< T >::reverse_iterator", null, null ],
    [ "vector< T >::reverse_iterator", null, null ],
    [ "u8string_view::reverse_iterator", null, null ],
    [ "string_view::reverse_iterator", null, null ],
    [ "set< K >::reverse_iterator", null, null ],
    [ "unordered_multimap< K, T >::reverse_iterator", null, null ],
    [ "basic_string_view< Char >::reverse_iterator", null, null ],
    [ "map< K, T >::reverse_iterator", null, null ],
    [ "wstring_view::reverse_iterator", null, null ],
    [ "multiset< K >::reverse_iterator", null, null ],
    [ "wstring::reverse_iterator", null, null ],
    [ "RuntimeParameters", "classsl_1_1RuntimeParameters.html", null ],
    [ "SensorParameters", "structsl_1_1SensorParameters.html", null ],
    [ "SensorsConfiguration", "structsl_1_1SensorsConfiguration.html", null ],
    [ "SensorsData", "structsl_1_1SensorsData.html", null ],
    [ "set< K >", null, null ],
    [ "shared_lock< T >", null, null ],
    [ "shared_mutex", null, null ],
    [ "shared_ptr< T >", null, null ],
    [ "shared_timed_mutex", null, null ],
    [ "smart_ptr< T >", null, null ],
    [ "span< T >", null, null ],
    [ "SpatialMappingParameters", "classsl_1_1SpatialMappingParameters.html", null ],
    [ "stack< T >", null, null ],
    [ "StreamingParameters", "structsl_1_1StreamingParameters.html", null ],
    [ "system_error", null, null ],
    [ "TemperatureSensorData", "structsl_1_1TemperatureSensorData.html", null ],
    [ "thread", null, null ],
    [ "timed_mutex", null, null ],
    [ "unique_lock< T >", null, null ],
    [ "unique_ptr< T >", null, null ],
    [ "unordered_map< K, T >", null, null ],
    [ "unordered_multimap< K, T >", null, null ],
    [ "unordered_multiset< K >", null, null ],
    [ "unordered_set< K >", null, null ],
    [ "valarray< T >", null, null ],
    [ "vector< T >", null, null ],
    [ "weak_ptr< T >", null, null ],
    [ "ZEDCommon", "classsl_1_1ZEDCommon.html", null ],
    [ "Generic", null, null ],
    [ "Generic", null, null ],
    [ "InteropServices", null, null ],
    [ "InteropServices", null, null ],
    [ "InteropServices", null, null ],
    [ "K", null, null ],
    [ "Numerics", null, null ],
    [ "Numerics", null, null ],
    [ "Reflection", null, null ],
    [ "System", null, null ],
    [ "T", null, null ]
];